# Use Node 20 Alpine
FROM node:20-alpine

# Set Working Directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install Dependencies
RUN npm install 

#Cop Project Files
COPY . .

#Expose Backend Port
EXPOSE 7555

#Start Server With Hot-Reload
CMD ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/index.ts"]