

services:
  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_gui
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on: 
      - redis

  backend:
    build: .
    container_name: node_app
    restart: always
    ports: 
      - "7555:7555"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      - redis

volumes:
  redis_data:
