name: CI/CD Pipeline

on:
  push:
    branches:
      - main #runs pipeline only when pushing to main branch


jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
       - name: Checkout repository
         uses: actions/checkout@v3

      # 2. Setup Nodejs
       - name: Setup Nodejs
         uses: actions/checkout@v3
         with:
            node-version: "18"

      # 3. Install dependencies
       - name: Install dependencies
         run: npm ci

      # 4. Run tests
       - name: Run tests
         run: npm test

      # 5. Lint
       - name: Run lint
         run: npm run lint || echo "No lint script found"

      # 6. Build Docker Image locally
       - name: Build Docker Image
         run: docker build -t myapp .

      # 7. Trigger render deployment
       - name: Deploy to Render
         run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{"serviceId": "${{ secrets.RENDER_SERVICE_ID }}"}' \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys